# Skill 全局配置文件
# 支持两种格式：
# 1. 全局配置：key: value
# 2. 按 skill 分组：skillName.key: value

# ========== 全局配置 ==========
# 这些配置会被所有 skill 读取
# 日志配置
log.level: info

# ========== 沙箱环境配置 ==========
# 为特定 skill 配置沙箱环境变量
skills:
  s3-upload:
    env:
      S3_REGION: oss-cn-shanghai
      S3_ACCESS_KEY: LTAI5tJWbBo61D1B3zxvL2Wa
      S3_SECRET_KEY: chtHRmKBR1AdpR0j0tNUh7KVnCMeAy
      S3_BUCKET: xdata-test
      S3_ENDPOINT: https://oss-cn-shanghai.aliyuncs.com
